### ISSUE TITLE
Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by gonzarthegreat** [hooram/ownphotos#30]
When attempting to login with latest build, receive the following:

Chrome: "Cannot read property 'status' of undefined"
Firefox: "e.response is undefined"
IE: "Unable to get property 'status' of undefined or null reference"

Login does not complete

**Comment by hooram** [comment]
Do you mean the latest build being `hooram/ownphotos:dev`? I wouldn't recommend running that because it might not have all the necessary changes reflected. Either way, I pushed some changes that should fix the problem. See 60eaae8027bd5af4fc7e107b76a39a13c78f4897.

**Comment by gonzarthegreat** [comment]
FYI, tried both main and the latest dev (with your proposed patch), I still see same issue.

**Comment by xbLyed** [comment]
It is fixed for me now.

**Comment by gonzarthegreat** [comment]
I appreciate you sharing time.  I have followed your instructions, problem still exists.  

I next started with a fresh new VM/docker and applied latest dev against it (in case I was still missing something) with your exact instructions above, still seeing same issue.

Is there an embedded log I can parse out to try and get better details on the error?

**Comment by alex-phillips** [comment]
@gonzarthegreat are you running it in HTTPS by chance?

**Comment by Drudoo** [comment]
Getting the exact same error. Tried both readme instructions and what’s mentioned above here. 
Both gives me the error on a brand new server running docker on Ubuntu.

**Comment by gonzarthegreat** [comment]
As previously mentioned, connecting straight to the port (versus through Nginx proxy where may or may not do HTTPs) still shows error.

Issue exists on both Ubuntu 17 & 16 docker base.

What base Linux are you running where are this successful?

**Comment by edoaxyz** [comment]
I think that JS is doing a request to the wrong url, because the url that's requesting (http://localhost/api/auth/token/obtain/) doesn't point to anything, while the correct url is http://localhost:8000/api/auth/token/obtain/ which points to API.
![image](https://user-images.githubusercontent.com/17519322/44030842-574a3bba-9f02-11e8-9343-0c0234580552.png)

**Comment by thejacer87** [comment]
im running into the same issue right now. just setup a brand new postgres, redis and ownphotos dockers

**Comment by RiRomain** [comment]
You're right, it's a problem of port.

If you change the backend docker run call to listen on port 80 instead of  8000 (by using -p 80:80), then it work.
If you have an nginx instance, redirecting port 80 to port 8000 like in the instruction, then it also does work.
What the instruction miss to say, is that you need this redirection, otherwise it doesn't work.

But for now, if you don't have any other service listening on port 80, you can simply use the port 80 instead of 8000.

**Comment by rom1504** [comment]
I just had this problem. For information, ownphotos doesn't support https on the backend. So you need to remove the http -> https redirection and it works. (just insecurely)

**Comment by gregbert42** [comment]
I have tried to get this to work every which way - using the .yaml above, using the exact lines from hooram's post above - but i always get exactly the same thing - "Cannot read property 'status' of undefined"
Really wanted to get this running...

**Comment by 2nutz4u** [comment]
I have the same problem. Any updates? Anyone able to resolve this issue or have working installation guide. I have done numerous install on Ubuntu 16.04 and with all suggestion above but still getting the same error.

**Comment by guysoft** [comment]
I solved it here.
The issue is that you should not install from master (yet).
Last week the updated docker has been merged and I suggest you use that.
This error tends to appear if the frontend can't connect to the backed, if there is CORS problems and more. Using the docker deployment solves all this.
Please follow this:
https://github.com/hooram/ownphotos-frontend/issues/8#issuecomment-447003146

I suggest you try these two lines and try and deploy that way, confirmed its fixes and we can close this.
